### ISSUE TITLE
Compatibility with brick/phonenumber 0.5.0

### ISSUE THREAD

**Issue by hvanoch** [brick/phonenumber-doctrine#1]
Is there a reason why this library can not be installed with the latest brick/phonenumber version?
`
brick/phonenumber-doctrine 0.1.3 requires brick/phonenumber ~0.2.0 || ~0.3.0 || ~0.4.0
`

**Comment by BenMorel** [comment]
Hi, definitely not, I just forgot to update this package. PR welcome!

**Comment by BenMorel** [comment]
Fixed in [0.2.0](https://github.com/brick/phonenumber-doctrine/releases/tag/0.2.0)!
